# -*- coding: utf-8 -*-
"""
卡片图渲染（Pillow）
布局模仿参考模板：渐变背景 + 居中圆角卡片 + 顶部标题 + 键值对表格 + 底部来源小字。
只学布局结构，不复制原图内容。
"""

import os
import re

from PIL import Image, ImageDraw, ImageFont

# 剥离字形（微软雅黑）不支持的 emoji / 零宽连接符 / 变体选择符，避免渲染成"口"
_EMOJI_RE = re.compile(r"[\U0001F000-\U0001FAFF\u2600-\u27BF\uFE0F\u200D\uFE0E\uFE0F]")


def _clean_text(value) -> str:
    return _EMOJI_RE.sub("", str(value)).strip()

# ── 尺寸常量 ──
W = 880
MARGIN = 36          # 卡片距图片边缘
PAD = 48             # 卡片内边距
TITLE_SIZE = 42
SUB_SIZE = 26
LABEL_SIZE = 27
VALUE_SIZE = 27
CARD_W = W - MARGIN * 2

# ── 颜色 ──
BG_TOP = (224, 244, 255)      # 背景顶部（浅天蓝）
BG_BOTTOM = (154, 211, 255)   # 背景底部（天蓝）
CARD_BG = (255, 255, 255)
TITLE_COLOR = (17, 24, 39)
LABEL_COLOR = (120, 130, 145)
VALUE_COLOR = (31, 41, 55)
FILL_COLOR = (148, 163, 184)   # 表格分隔线
FOOT_COLOR = (148, 163, 184)
GITHUB_COLOR = (36, 41, 46)

FONT_BASE = "C:/Windows/Fonts/msyh.ttc"       # 微软雅黑
FONT_BOLD = "C:/Windows/Fonts/msyhbd.ttc"     # 微软雅黑粗体


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for path in ([FONT_BOLD if bold else FONT_BASE, "C:/Windows/Fonts/simhei.ttf"]):
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default()


def _text_columns(value: str, font, max_width: int) -> list:
    """
    按可用宽度把长文本折成多行。
    - 支持显式 \n 换行（每个段落分别折行）
    - 英文/数字优先在空格处断行，避免单词被硬切（如 "to" 中间断开）
    """
    lines = []
    for seg in _clean_text(value).split("\n"):
        cur = ""
        for ch in seg:
            if cur and font.getlength(cur + ch) > max_width:
                if " " in cur:
                    sp = cur.rfind(" ")  # 从空格处断开，保英文单词完整
                    head, cur = cur[:sp], cur[sp + 1:]
                    lines.append(head)
                else:
                    lines.append(cur)
                    cur = ch
                    continue
            cur += ch
        lines.append(cur)
    return [ln for ln in lines if ln != ""] or [""]


def render_card(
    title: str,
    rows,
    out_path: str,
    subtitle: str = None,
    footer: str = "Generated by ZSE.Bot · GitHub",
):
    """
    渲染一张通知卡片图。

    Args:
        title: 卡片主标题（如 "新的拉取请求"）
        rows:  [(标签, 值), ...] 键值对，值过长会自动折行
        out_path: 输出 png 路径
        subtitle: 标题下的副标题（可选，如仓库名）
        footer: 底部来源小字
    """
    title_font = _font(TITLE_SIZE, bold=True)
    sub_font = _font(SUB_SIZE)
    label_font = _font(LABEL_SIZE)
    value_font = _font(VALUE_SIZE)
    foot_font = _font(22)

    # ── 先估算高度 ──
    inner_w = CARD_W - PAD * 2
    label_w = 160
    value_w = inner_w - label_w - 20
    row_heights = []
    for label, value in rows:
        value_lines = _text_columns(value, value_font, value_w)
        row_heights.append(max(52, len(value_lines) * 40 + 12))

    head_h = (TITLE_SIZE + 8 + (40 if subtitle else 0) + 24)
    table_h = sum(row_heights)
    foot_h = 46
    card_inner_h = PAD + head_h + table_h + foot_h + PAD
    card_h = card_inner_h
    H = card_h + MARGIN * 2

    img = Image.new("RGB", (W, H), BG_TOP)
    draw = ImageDraw.Draw(img)

    # ── 渐变背景 ──
    for y in range(H):
        t = y / max(1, H - 1)
        color = tuple(int(BG_TOP[i] + (BG_BOTTOM[i] - BG_TOP[i]) * t) for i in range(3))
        draw.line([(0, y), (W, y)], fill=color)

    # ── 背景简单装饰：两朵淡白云朵（只增氛围，不抄原图）──
    _deco = Image.new("L", (W, H), 0)
    _dd = ImageDraw.Draw(_deco)
    _dd.ellipse((110, 60, 330, 160), fill=120)
    _dd.ellipse((560, 150, 760, 230), fill=90)
    deco_rgba = Image.new("RGBA", (W, H), (255, 255, 255, 0))
    deco_over = Image.composite(deco_rgba, img.convert("RGBA"), _deco.point(lambda p: 0 if p < 32 else p * 2))
    img = deco_over.convert("RGB")
    draw = ImageDraw.Draw(img)

    # ── 卡片 ──
    card_box = (MARGIN, MARGIN, W - MARGIN, MARGIN + card_h)
    draw.rounded_rectangle(card_box, radius=26, fill=CARD_BG)

    y = MARGIN + PAD

    # ── 标题（居中）──
    tw = draw.textlength(title, font=title_font)
    draw.text(((W - tw) / 2, y), title, font=title_font, fill=TITLE_COLOR)
    y += TITLE_SIZE + 8
    if subtitle:
        sw = draw.textlength(subtitle, font=sub_font)
        draw.text(((W - sw) / 2, y), subtitle, font=sub_font, fill=GITHUB_COLOR)
        y += SUB_SIZE + 12
    else:
        y += 12

    # ── 表格：键值对行 ──
    rows_origin = y
    for i, ((label, value), rh) in enumerate(zip(rows, row_heights)):
        # 行分隔线
        if y > rows_origin:
            draw.line([(MARGIN + PAD, y), (W - MARGIN - PAD, y)], fill=FILL_COLOR, width=1)
        draw.text((MARGIN + PAD, y + 6), label, font=label_font, fill=LABEL_COLOR)
        lines = _text_columns(str(value), value_font, value_w)
        ly = y + 6
        for line in lines:
            draw.text((MARGIN + PAD + label_w + 20, ly), line, font=value_font, fill=VALUE_COLOR)
            ly += 40
        y += rh

    # ── 底部来源 ──
    fw = draw.textlength(footer, font=foot_font)
    draw.text(((W - fw) / 2, MARGIN + card_h - foot_h - 10), footer, font=foot_font, fill=FOOT_COLOR)

    img.save(out_path, "PNG")
    return out_path